on: push

jobs:
  download-and-upload:
    name: Runner
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Install R
        uses: r-lib/actions/setup-r@v1
        with:
            r-version: '4.0.3' # The R version to download (if necessary) and use.

      - name: Install dev lib dependencies
        run: |
          sudo apt-get install libpoppler-cpp-dev # used by 'pdftools'
          sudo apt-get install libcurl4-openssl-dev # used by 'tidyverse'

      - name: Install R dependencies
        run: |
          install.packages("remotes")
          remotes::install_cran("tidyverse")
          remotes::install_cran("pdftools")
          remotes::install_cran("assertthat")
          install.packages(c("tidyverse","pdftools","assertthat"))
        shell: Rscript {0}

      - name: Download and process the PDF
        run: |
          source("R/get_ga_dph_vaccine_orders_list.R")
        shell: Rscript {0}
